import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faMugHot } from "@fortawesome/free-solid-svg-icons";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="mb-8">
          <div className="flex justify-between max-w-xl mx-auto px-4 py-4">
            <Link
              className="inline-flex gap-1 flex-row-reverse items-center"
              href={"/"}
            >
              <FontAwesomeIcon
                className="h-8 text-yellow-400"
                icon={faMugHot}
              />
              <span className="mt-2">Buy me a tea</span>
            </Link>
            <nav className="mt-2 flex gap-4 items-center">
              <Link className="" href={"/about"}>
                About
              </Link>
              <Link className="" href={"/faq"}>
                FAQ
              </Link>
              <div className="flex gap-4">
                <button className="ml-2 border-s-2 border-slate-200 pl-4">
                  Login
                </button>
                <button className="bg-yellow-400 rounded-full px-4 py-2">
                  Sign Up
                </button>
              </div>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
